# -*- coding: utf-8 -*-
"""voronoi_diagram_soccer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvGbqUucE_CiZmIGkA9iUaZuyOSqYQM0
"""

!pip install mplsoccer

#import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mplsoccer.pitch import Pitch, VerticalPitch

import numpy as np
import pandas as pd

barca_x = [93, 96, 99, 102, 104, 95, 86, 79, 89]
barca_y = [9, 22, 33, 44, 56, 63, 52, 33, 22]
barca = np.zeros(len(barca_x)).astype(int)

opp_x = [99, 100, 102, 104, 104, 102, 97, 98, 94,77]
opp_y = [14, 22, 33, 43, 46, 55, 37, 27, 21,45]
opp = np.ones(len(opp_x)).astype(int)



df = pd.DataFrame({
    'x': np.concatenate([barca_x, opp_x]),
    'y': np.concatenate([barca_y, opp_y]),
    'team': np.concatenate([barca, opp])
})

df

fig, ax = plt.subplots(figsize = (13,8.5))

pitch = Pitch(pitch_type='statsbomb', half=True,
              pitch_color = 'black', line_color = 'white',
              axis=True, label=True, tick = True)
pitch.draw(ax=ax, constrained_layout=False)

pitch.scatter(93,9, ax=ax)

df

points = np.column_stack((df.x,df.y))

points

import matplotlib.pyplot as plt
from mplsoccer import Pitch, VerticalPitch

fig, ax = plt.subplots(figsize=(13,8.5))
fig.set_facecolor('#38383b')
ax.patch.set_facecolor('#38383b')

pitch = VerticalPitch(pitch_type='statsbomb', half=True,
              pitch_color='black', line_color='white')

pitch.draw(ax=ax, constrained_layout=False)


x = df.x
y = df.y
team1 , team2 = pitch.voronoi(x, y, df.team)

t1 = pitch.polygon(team1, ax=ax, fc='red', ec='white', lw=3, alpha=.4)
t2 = pitch.polygon(team2, ax=ax, fc='blue', ec='white', lw=3, alpha=.4)